# Asthma Prevalence 

Libraries:
```{r}
library(tidyverse)
library(janitor)
library(dplyr)
library(ggplot2)
prev_clean <- readRDS("prev_clean.rds")

```


First plot: 
```{r}

prev_statewide <- dplyr::filter(prev_clean, county == "California")


ggplot(prev_statewide, aes(x = years_period, y = prevalence, group = 1)) +
  geom_line(size = 1.2, color = "#1D6996") +
  geom_point(size = 3, color = "#1D6996") +
  labs(
    title = "Statewide Current Asthma Prevalence in California (CHIS)",
    subtitle = "Two-year period estimates, 2015–2022",
    x = "Two-Year Period",
    y = "Prevalence (%)"
  ) +
  theme_minimal(base_size = 14) +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1)
  )

```

Second Plot: 
```{r}
prev_counties <- prev_clean |> dplyr::filter(county != "California")


ggplot(prev_counties, aes(x = years_period, y = prevalence, group = county)) +
  geom_line(alpha = 0.4, color = "#5DA5DA") +
  labs(
    title = "Asthma Prevalence by County, 2015–2022",
    subtitle = "Each line represents one county",
    x = "Two-Year Period",
    y = "Prevalence (%)"
  ) +
  theme_minimal(base_size = 14) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

Third Plot: 
```{r}
interesting <- c("Fresno", "Los Angeles", "Marin", "Butte", "Kern", "San Francisco")

prev_focus <- prev_clean |>
  dplyr::filter(county %in% interesting)

ggplot(prev_focus, aes(x = years_period, y = prevalence, color = county, group = county)) +
  geom_line(size = 1.2) +
  geom_point(size = 2) +
  labs(
    title = "Asthma Prevalence for Selected Counties (2015–2022)",
    x = "Two-Year Period",
    y = "Prevalence (%)",
    color = "County"
  ) +
  theme_minimal(base_size = 14) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

Fourth Plot: 
```{r}
ggplot(prev_counties, aes(x = years_period, y = county, fill = prevalence)) +
  geom_tile() +
  scale_fill_viridis_c(option = "C") +
  labs(
    title = "Heatmap of Asthma Prevalence by County (2015–2022)",
    x = "Two-Year Period",
    y = "County",
    fill = "Prevalence (%)"
  ) +
  theme_minimal(base_size = 14) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

